{
  /**
   * Generated by scripts/generateHaptics.php - do not edit manually
   * https://github.com/Apotheneum/Apotheneum
   */

  "label": "Haptics",
  "tag": "haptics",
  "components": [
    {
      "type": "points",
      "coords": [
<?php
$points = array();
$vertices = array();
$sides = array();

$sin60 = sin(deg2rad(60));
$cos60 = cos(deg2rad(60));
$height = 36 * $sin60;
$midpoint = 18 * tan(deg2rad(30));

for ($r = 0; $r < 8; ++$r) {
  $i = ($r < 4) ? $r : (7-$r);
  $n = (9 + 2*$i);
  $flip = $r < 4;

  for ($c = 0; $c < $n; ++$c) {
    $x = 18 * ($c - ($n-1)/2);

    $yb = $height * ($r - 4);
    $yc = $yb + $height * .5;
    $y = $yb + ($flip ? ($height - $midpoint) : $midpoint);

    $inset = 2.0 / 36.0;
    $xin = 36 * $inset;
    $yin = $height * $inset;

    $x0 = $x - 18 + $xin;
    $x1 = $x + 18 - $xin;
    $y0 = $yc - $height/2 + $cos60 * $yin;
    $y1 = $yc + $height/2 - $sin60 * $yin;
    $z = 1;
    $zd = .5;

    $points []= '        { "x": '.$x.', "y": '.$y.' }';



    if ($flip) {
      $v1x = $x0;
      $v2x = $x;
      $v3x = $x1;
      $v1y = $y1;
      $v2y = $y0;
      $v3y = $y1;
    } else {
      $v1x = $x0;
      $v2x = $x1;
      $v3x = $x;
      $v1y = $y0;
      $v2y = $y0;
      $v3y = $y1;
    }
    $vertices []= '        { "x": '.$v1x.', "y": '.$v1y.', "z": '.$z.' }';
    $vertices []= '        { "x": '.$v2x.', "y": '.$v2y.', "z": '.$z.' }';
    $vertices []= '        { "x": '.$v3x.', "y": '.$v3y.', "z": '.$z.' }';

    $sides []=  '        { "x": '.$v1x.', "y": '.$v1y.', "z": '.$z.' }';
    $sides []=  '        { "x": '.$v1x.', "y": '.$v1y.', "z": '.$z+$zd.' }';
    $sides []= '        { "x": '.$v2x.', "y": '.$v2y.', "z": '.$z.' }';
    $sides []=  '        { "x": '.$v1x.', "y": '.$v1y.', "z": '.$z+$zd.' }';
    $sides []= '        { "x": '.$v2x.', "y": '.$v2y.', "z": '.$z.' }';
    $sides []= '        { "x": '.$v2x.', "y": '.$v2y.', "z": '.$z+$zd.' }';

    $sides []= '        { "x": '.$v2x.', "y": '.$v2y.', "z": '.$z.' }';
    $sides []= '        { "x": '.$v2x.', "y": '.$v2y.', "z": '.$z+$zd.' }';
    $sides []= '        { "x": '.$v3x.', "y": '.$v3y.', "z": '.$z.' }';
    $sides []= '        { "x": '.$v2x.', "y": '.$v2y.', "z": '.$z+$zd.' }';
    $sides []= '        { "x": '.$v3x.', "y": '.$v3y.', "z": '.$z.' }';
    $sides []= '        { "x": '.$v3x.', "y": '.$v3y.', "z": '.$z+$zd.' }';

    $sides []= '        { "x": '.$v3x.', "y": '.$v3y.', "z": '.$z.' }';
    $sides []= '        { "x": '.$v3x.', "y": '.$v3y.', "z": '.$z+$zd.' }';
    $sides []= '        { "x": '.$v1x.', "y": '.$v1y.', "z": '.$z.' }';
    $sides []= '        { "x": '.$v3x.', "y": '.$v3y.', "z": '.$z+$zd.' }';
    $sides []= '        { "x": '.$v1x.', "y": '.$v1y.', "z": '.$z.' }';
    $sides []= '        { "x": '.$v1x.', "y": '.$v1y.', "z": '.$z+$zd.' }';

    $flip = !$flip;
  }
}
echo implode(",\n", $points);
?>
      ]
    }
  ],

  "ui": {
    "meshes": [
      {
        "type": "uniformFill",
        "color": "0xff141414",
        "vertices": [
  <?php echo implode(",\n", $vertices )."\n"; ?>
        ]
      },
      {
        "type": "uniformFill",
        "color": "0xff332011",
        "vertices": [
  <?php echo implode(",\n", $sides )."\n"; ?>
        ]
      }
    ]
  }
}
