{  
  /**
   * Generated by scripts/generateHaptics.php - do not edit manually
   * https://github.com/Apotheneum/Apotheneum
   */
  
  "label": "Haptics",
  "tag": "haptics",
  "components": [
    {
      "type": "points",
      "coords": [
<?php
$points = array();
$vertices = array();

$sin60 = sin(deg2rad(60));
$cos60 = cos(deg2rad(60));
$height = 36 * $sin60;
$midpoint = 18 * tan(deg2rad(30));

for ($r = 0; $r < 8; ++$r) {
  $i = ($r < 4) ? $r : (7-$r);
  $n = (9 + 2*$i);
  $flip = $r < 4;
  
  for ($c = 0; $c < $n; ++$c) {
    $x = 18 * ($c - ($n-1)/2);
    
    $zb = $height * ($r - 4);
    $zc = $zb + $height * .5;
    $z = $zb + ($flip ? ($height - $midpoint) : $midpoint);
        
    $inset = 2.0 / 36.0;
    $xin = 36 * $inset;
    $zin = $height * $inset;
    
    $x0 = $x - 18 + $xin;
    $x1 = $x + 18 - $xin;
    $z0 = $zc - $height/2 + $cos60 * $zin;
    $z1 = $zc + $height/2 - $sin60 * $zin;
    $y = -1;    
    
    $points []= '        { "x": '.$x.', "z": '.$z.' }';
    if ($flip) {
      $vertices []= '        { "x": '.$x0.', "y": '.$y.', "z": '.$z1.' }';
      $vertices []= '        { "x": '.$x.', "y": '.$y.', "z": '.$z0.' }';
      $vertices []= '        { "x": '.$x1.', "y": '.$y.', "z": '.$z1.' }';
    } else {
      $vertices []= '        { "x": '.$x0.', "y": '.$y.', "z": '.$z0.' }';
      $vertices []= '        { "x": '.$x1.', "y": '.$y.', "z": '.$z0.' }';
      $vertices []= '        { "x": '.$x.', "y": '.$y.', "z": '.$z1.' }';
    }
    
    $flip = !$flip;
  }
}
echo implode(",\n", $points);
?>      
      ]
    }
  ],
  
  "ui": {
    "mesh": {
      "type": "uniformFill",
      "color": "0xff141414",
      "vertices": [
<?php echo implode(",\n", $vertices )."\n"; ?>
      ]
    }
  }
}
